Reviews in every SubjectCard
domukas44/University-Advisor pull request #7
Opened 2019-10-19 09:22 UTC by gaju5502

2019-10-19 14:35 UTC, domukas44 commented
atrodo viskas gerai ir veikia :)

2019-10-20 08:35 UTC, mrzilvis commented on Controllers/Subject.cs
> +        //changes by Dominykas
nebutina komentuoti, kieno tie pakeitimai, nes matosi kas, ka ir kada keite :)

2019-10-20 08:39 UTC, mrzilvis requested changes
Jeigu nereikalingas tuscias metodas UpdateRating, tai istrink

2019-10-20 08:39 UTC, mrzilvis commented on View/Menu.cs
> +        public void UpdateRating(double rating, string name)
kam sitas tuscias metodas?

2019-10-20 08:43 UTC, mrzilvis commented
![image](https://user-images.githubusercontent.com/17772723/67157027-c8895780-f32e-11e9-982d-6ab18f100d39.png)

blogai apskaiciuojami/atvaizduojami rezultatai

2019-10-20 08:49 UTC, gaju5502 commented
> ![image](https://user-images.githubusercontent.com/17772723/67157027-c8895780-f32e-11e9-982d-6ab18f100d39.png)
> 
> blogai apskaiciuojami/atvaizduojami rezultatai

o čia negali būt su lokalizacija susiję? nes pas mane viską ok rodo

2019-10-20 10:06 UTC, merged